FROM php:8.1.3-cli-alpine 

RUN apk --no-cache add autoconf gcc g++ file make git mosquitto-dev\
    && git clone https://github.com/ronfoerster/Mosquitto-PHP-1.git --branch php-8.1 /mosquitto-php \
    && cd /mosquitto-php \
    && phpize \
    && ./configure \
    && make \
    && make install \
    && echo "extension=mosquitto.so" > /usr/local/etc/php/conf.d/mosquitto-php.ini \
    && rm -rf /mosquitto-php

CMD ["/bin/sh"]
