name: Build Extension

on:
  push:
    branches: [ php8 ]
  pull_request:
    branches: [ php8 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP-8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: phpize
    - name: phpize
      run: phpize 
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
