name: Build and Test Extension

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install -y mosquitto libmosquitto-dev
    - uses: actions/checkout@v2
    - name: Setup PHP-8.0
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: phpize
    - name: Build extension
      run: |
        phpize
        ./configure
        make
    - name: Run tests
      run: |
        export NO_INTERACTION=1
        export REPORT_EXIT_STATUS=1
        sudo systemctl stop mosquitto
        cd tests
        ./makeTestCerts.sh
        sudo chown -R runner:runner certs
        mosquitto -c mosquitto.conf -d
        cd ..
        php -n -d "extension_dir=./modules/" -d "extension=mosquitto.so" ./tests/Client/publish.phpt
        make test
