name: Test-Matrix

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['8.1'] #'7.4', '8.0',
        mosquitto-versions: ['2.0.14']
    steps:
    - uses: actions/checkout@v2
    - name: Start Mosquitto
      uses: docker://eclipse-mosquitto:2-openssl
      with:
        #entrypoint: usr/local/bin/echo
        args: -p 1883:1883  -p 8883:8883 -p 8884:8884 -p 8885:8885 -v ${{ github.workspace }}/tests:/mosquitto/config -v ${{ github.workspace }}/tests/lib:/usr/lib
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: phpize
    - name: Build extension
      run: |
        phpize
        ./configure --with-mosquitto=tests/lib
        make
    - name: Run tests
      run: |
        export NO_INTERACTION=1
        export REPORT_EXIT_STATUS=1
        make test
